import Head from 'next/head'
import Contents from '../components/Contents';
import Header from '../components/Header'
import Nav from '../components/Nav'

export default function Home({ contents }) {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 헤더 */}
      <Header />

      {/* 메뉴 */}
      <Nav />

      {/* 컨텐츠 */}
      <Contents contents={contents}/>

    </div>
  )
}

export async function getServerSideProps(context: { query: { menu: any; }; }) {

  const menu = context.query.menu;

  const BASE_URL = 'https://api.themoviedb.org';
  const API_KEY = '940b46cd1ee7213b55c2b72f2e0d3acf';

  const res = await fetch(`${BASE_URL}/3/discover/movie?api_key=${API_KEY}&language=kr&with_genres=${menu}`)
  const data = await res.json()
  return {
      props: {
          contents: data.results
      },
  }
}